#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', 0);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');


Yii::setAlias('common', __DIR__.'/common');


Yii::setAlias('@console', __DIR__ . '/console');

//$config = require(__DIR__ . '/common/config/console.php');

$config = require(__DIR__ . '/console/config/console.php');


$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
